#!/bin/bash

for p in $(find . -maxdepth 1 -type d | grep -v "^\\.$" | grep -v ".idea" | grep -P "[\d]+" | sort -u)
do
	echo -e $p
	cd $p
	
	nano README
	git commit -am 'updated pom' && git push origin
	
	cd ..
done
