#!/bin/bash

_setup_() {
	git submodule add git@github.com:walterjwhite/${1}.git
}

#_setup_ datetime
#_setup_ pipe
#_setup_ shell
#_setup_ serialization
#_setup_ encryption
#_setup_ csv
#_setup_ index
#_setup_ ssh
#_setup_ queue
#_setup_ file
#_setup_ google
#_setup_ amazon
_setup_ compression
