#!/bin/bash

# remove our artifacts
rm -Rf ~/.m2/repository/com/walterjwhite

# automatically format Java code
if [ -e /usr/bin/format-java-code ]
then
	echo -e "formatting Java code"
	/usr/bin/format-java-code
fi

# required for qulice
touch /tmp/license.txt
#if [ "$#" -ge "1" ]
#then
	_options="-Dmaven.test.skip=true"
#fi

# setup some dummy values so the properties are at least set
#./setup-environment
mvn clean install $_options

exit $?
